### PR TITLE
Week5 exercises

### PR DESCRIPTION
**Pull request by pschwllr**
Let's discuss the exercises here.

### CODE REVIEW

**Comment by pschwllr** [comment]
@sarina-kopf Can you change all `asprin` to `aspirin`?

**Comment by sarina-kopf** [comment]
Fixed the asprin typo, I also added a little plugin for 3D rendering, which shows that rdkit is doing its best to match the 3D structure it's just terrible at visualizing it.

**Comment by rneeser** [comment]
Can't for some reason review in code sorry. Will do in comment section here.

**Atom mapping**
[code](https://github.com/schwallergroup/practical-programming-in-chemistry-exercises/blob/20e3a4c92e8b523a504572a44592bd03a989a6c7/week_05/05_solutions.ipynb#L6058C1-L6066C43)
Atom map number zero does not exist (means there is not map set) so one should always offset by one when mapping based on atom indices. That's why one of the carbonyl O's does not have a number.

**Comment by rneeser** [comment]
**SMILES intro**
I would point them to some link explaining SMILES or add an image showing the concept. Like this it's probably too much asked. Could be the daylight docs or an image [like this](https://bioicons.com/icons/cc-0/Molecular_modelling/Simon_Dürr/smiles.svg)

**Comment by rneeser** [comment]
**Descriptors**
[Intro](https://github.com/schwallergroup/practical-programming-in-chemistry-exercises/blob/20e3a4c92e8b523a504572a44592bd03a989a6c7/week_05/05_solutions.ipynb#L6075C5-L6075C71): Maybe add one sentence what a descriptor is.

[Typo](https://github.com/schwallergroup/practical-programming-in-chemistry-exercises/blob/20e3a4c92e8b523a504572a44592bd03a989a6c7/week_05/05_solutions.ipynb#L6853C53-L6853C60): senese -> sense

**Pull request merged**
